#!/bin/sh
chmod +x ./hooks/*
git add ./hooks/

rm ./CHANGELOG.md
git log --format="* %s" --no-merges $(git describe --tags --abbrev=0 @^)..@ >> ./CHANGELOG.md
git add ./CHANGELOG.md

# Prettify all files
FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.jsx" "*.json" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0
echo "$FILES" | xargs ./node_modules/.bin/prettier --write
echo "$FILES" | xargs git add


